version: 2
updates:
  # Enable version updates for npm/yarn
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every Sunday
    schedule:
      interval: 'weekly'
      day: 'sunday'
    # Base branch to use in pull requests for version updates
    target-branch: 'dependabot-base'
